/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/admin/[...all]': RouteRecordInfo<
      '/admin/[...all]',
      '/admin/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/admin/company/addresses': RouteRecordInfo<
      '/admin/company/addresses',
      '/admin/company/addresses',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/company/banks': RouteRecordInfo<
      '/admin/company/banks',
      '/admin/company/banks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/customers': RouteRecordInfo<
      '/admin/customers',
      '/admin/customers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/Dashboard': RouteRecordInfo<
      '/admin/Dashboard',
      '/admin/Dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/forgot-password': RouteRecordInfo<
      '/admin/forgot-password',
      '/admin/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/inventory/Shipping': RouteRecordInfo<
      '/admin/inventory/Shipping',
      '/admin/inventory/Shipping',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/inventory/Stock': RouteRecordInfo<
      '/admin/inventory/Stock',
      '/admin/inventory/Stock',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/inventory/stock-adjusment': RouteRecordInfo<
      '/admin/inventory/stock-adjusment',
      '/admin/inventory/stock-adjusment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/login': RouteRecordInfo<
      '/admin/login',
      '/admin/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/partnership/Genealogy': RouteRecordInfo<
      '/admin/partnership/Genealogy',
      '/admin/partnership/Genealogy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/partnership/member-downgrades': RouteRecordInfo<
      '/admin/partnership/member-downgrades',
      '/admin/partnership/member-downgrades',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/partnership/member-registration': RouteRecordInfo<
      '/admin/partnership/member-registration',
      '/admin/partnership/member-registration',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/partnership/member-stock': RouteRecordInfo<
      '/admin/partnership/member-stock',
      '/admin/partnership/member-stock',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/partnership/member-upgrades': RouteRecordInfo<
      '/admin/partnership/member-upgrades',
      '/admin/partnership/member-upgrades',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/partnership/members': RouteRecordInfo<
      '/admin/partnership/members',
      '/admin/partnership/members',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/partnership/registration-approvals': RouteRecordInfo<
      '/admin/partnership/registration-approvals',
      '/admin/partnership/registration-approvals',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/partnership/sales-report': RouteRecordInfo<
      '/admin/partnership/sales-report',
      '/admin/partnership/sales-report',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/partnership/stockists': RouteRecordInfo<
      '/admin/partnership/stockists',
      '/admin/partnership/stockists',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/product/categories': RouteRecordInfo<
      '/admin/product/categories',
      '/admin/product/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/product/prices': RouteRecordInfo<
      '/admin/product/prices',
      '/admin/product/prices',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/product/products': RouteRecordInfo<
      '/admin/product/products',
      '/admin/product/products',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/profile': RouteRecordInfo<
      '/admin/profile',
      '/admin/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/report/cash-receipts': RouteRecordInfo<
      '/admin/report/cash-receipts',
      '/admin/report/cash-receipts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/report/inventory-value': RouteRecordInfo<
      '/admin/report/inventory-value',
      '/admin/report/inventory-value',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/report/profit-loss': RouteRecordInfo<
      '/admin/report/profit-loss',
      '/admin/report/profit-loss',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/reset-password': RouteRecordInfo<
      '/admin/reset-password',
      '/admin/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/rewards/annual': RouteRecordInfo<
      '/admin/rewards/annual',
      '/admin/rewards/annual',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/rewards/monthly': RouteRecordInfo<
      '/admin/rewards/monthly',
      '/admin/rewards/monthly',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/rewards/point-achievement-report': RouteRecordInfo<
      '/admin/rewards/point-achievement-report',
      '/admin/rewards/point-achievement-report',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/rewards/profit-sharing': RouteRecordInfo<
      '/admin/rewards/profit-sharing',
      '/admin/rewards/profit-sharing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/rewards/profit-sharing-history': RouteRecordInfo<
      '/admin/rewards/profit-sharing-history',
      '/admin/rewards/profit-sharing-history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/rewards/stockist': RouteRecordInfo<
      '/admin/rewards/stockist',
      '/admin/rewards/stockist',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/stc/saldo': RouteRecordInfo<
      '/admin/stc/saldo',
      '/admin/stc/saldo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/stc/topup': RouteRecordInfo<
      '/admin/stc/topup',
      '/admin/stc/topup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/system/administrators': RouteRecordInfo<
      '/admin/system/administrators',
      '/admin/system/administrators',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/system/commission-config': RouteRecordInfo<
      '/admin/system/commission-config',
      '/admin/system/commission-config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/system/menus': RouteRecordInfo<
      '/admin/system/menus',
      '/admin/system/menus',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/system/partnership-config': RouteRecordInfo<
      '/admin/system/partnership-config',
      '/admin/system/partnership-config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/system/roles': RouteRecordInfo<
      '/admin/system/roles',
      '/admin/system/roles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/transactions/payment-verification': RouteRecordInfo<
      '/admin/transactions/payment-verification',
      '/admin/transactions/payment-verification',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/transactions/sales-orders': RouteRecordInfo<
      '/admin/transactions/sales-orders',
      '/admin/transactions/sales-orders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/transactions/sales-returns': RouteRecordInfo<
      '/admin/transactions/sales-returns',
      '/admin/transactions/sales-returns',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/transactions/stock-screening': RouteRecordInfo<
      '/admin/transactions/stock-screening',
      '/admin/transactions/stock-screening',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/user-analytic/': RouteRecordInfo<
      '/admin/user-analytic/',
      '/admin/user-analytic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/[...all]': RouteRecordInfo<
      '/member/[...all]',
      '/member/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/member/Dashboard': RouteRecordInfo<
      '/member/Dashboard',
      '/member/Dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/forgot-password': RouteRecordInfo<
      '/member/forgot-password',
      '/member/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/login': RouteRecordInfo<
      '/member/login',
      '/member/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/menus/': RouteRecordInfo<
      '/member/menus/',
      '/member/menus',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/network/': RouteRecordInfo<
      '/member/network/',
      '/member/network',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/network/registrations/': RouteRecordInfo<
      '/member/network/registrations/',
      '/member/network/registrations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/network/registrations/[id]': RouteRecordInfo<
      '/member/network/registrations/[id]',
      '/member/network/registrations/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/member/notifications': RouteRecordInfo<
      '/member/notifications',
      '/member/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/profile/': RouteRecordInfo<
      '/member/profile/',
      '/member/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/profile/address': RouteRecordInfo<
      '/member/profile/address',
      '/member/profile/address',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/profile/address-form': RouteRecordInfo<
      '/member/profile/address-form',
      '/member/profile/address-form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/profile/bank': RouteRecordInfo<
      '/member/profile/bank',
      '/member/profile/bank',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/profile/bank-form': RouteRecordInfo<
      '/member/profile/bank-form',
      '/member/profile/bank-form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/profile/edit': RouteRecordInfo<
      '/member/profile/edit',
      '/member/profile/edit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/profile/partnership': RouteRecordInfo<
      '/member/profile/partnership',
      '/member/profile/partnership',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/profile/security': RouteRecordInfo<
      '/member/profile/security',
      '/member/profile/security',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/reset-password': RouteRecordInfo<
      '/member/reset-password',
      '/member/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/rewards/': RouteRecordInfo<
      '/member/rewards/',
      '/member/rewards',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/rewards/annual': RouteRecordInfo<
      '/member/rewards/annual',
      '/member/rewards/annual',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/rewards/monthly/': RouteRecordInfo<
      '/member/rewards/monthly/',
      '/member/rewards/monthly',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/rewards/monthly/[id]': RouteRecordInfo<
      '/member/rewards/monthly/[id]',
      '/member/rewards/monthly/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/member/rewards/sharing/': RouteRecordInfo<
      '/member/rewards/sharing/',
      '/member/rewards/sharing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/rewards/sharing/[id]': RouteRecordInfo<
      '/member/rewards/sharing/[id]',
      '/member/rewards/sharing/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/member/rewards/stockist/': RouteRecordInfo<
      '/member/rewards/stockist/',
      '/member/rewards/stockist',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/rewards/stockist/[id]': RouteRecordInfo<
      '/member/rewards/stockist/[id]',
      '/member/rewards/stockist/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/member/stock/': RouteRecordInfo<
      '/member/stock/',
      '/member/stock',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/stock/adjustment': RouteRecordInfo<
      '/member/stock/adjustment',
      '/member/stock/adjustment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/stock/mutation': RouteRecordInfo<
      '/member/stock/mutation',
      '/member/stock/mutation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/stock/returns/': RouteRecordInfo<
      '/member/stock/returns/',
      '/member/stock/returns',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/stock/returns/[id]': RouteRecordInfo<
      '/member/stock/returns/[id]',
      '/member/stock/returns/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/member/stock/returns/create': RouteRecordInfo<
      '/member/stock/returns/create',
      '/member/stock/returns/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/transactions/': RouteRecordInfo<
      '/member/transactions/',
      '/member/transactions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/transactions/goods-receipts/': RouteRecordInfo<
      '/member/transactions/goods-receipts/',
      '/member/transactions/goods-receipts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/transactions/goods-receipts/[id]': RouteRecordInfo<
      '/member/transactions/goods-receipts/[id]',
      '/member/transactions/goods-receipts/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/member/transactions/orders/': RouteRecordInfo<
      '/member/transactions/orders/',
      '/member/transactions/orders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/transactions/orders/[id]': RouteRecordInfo<
      '/member/transactions/orders/[id]',
      '/member/transactions/orders/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/member/transactions/orders/create': RouteRecordInfo<
      '/member/transactions/orders/create',
      '/member/transactions/orders/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/transactions/orders/payment': RouteRecordInfo<
      '/member/transactions/orders/payment',
      '/member/transactions/orders/payment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/transactions/sales/': RouteRecordInfo<
      '/member/transactions/sales/',
      '/member/transactions/sales',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/transactions/sales/[id]': RouteRecordInfo<
      '/member/transactions/sales/[id]',
      '/member/transactions/sales/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/member/transactions/sales/create': RouteRecordInfo<
      '/member/transactions/sales/create',
      '/member/transactions/sales/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/transactions/sales/payment': RouteRecordInfo<
      '/member/transactions/sales/payment',
      '/member/transactions/sales/payment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/transactions/sales/shipping': RouteRecordInfo<
      '/member/transactions/sales/shipping',
      '/member/transactions/sales/shipping',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'resources/js/admin/pages/[...all].vue': {
      routes:
        | '/admin/[...all]'
      views:
        | never
    }
    'resources/js/admin/pages/company/addresses.vue': {
      routes:
        | '/admin/company/addresses'
      views:
        | never
    }
    'resources/js/admin/pages/company/banks.vue': {
      routes:
        | '/admin/company/banks'
      views:
        | never
    }
    'resources/js/admin/pages/customers.vue': {
      routes:
        | '/admin/customers'
      views:
        | never
    }
    'resources/js/admin/pages/Dashboard.vue': {
      routes:
        | '/admin/Dashboard'
      views:
        | never
    }
    'resources/js/admin/pages/forgot-password.vue': {
      routes:
        | '/admin/forgot-password'
      views:
        | never
    }
    'resources/js/admin/pages/inventory/Shipping.vue': {
      routes:
        | '/admin/inventory/Shipping'
      views:
        | never
    }
    'resources/js/admin/pages/inventory/Stock.vue': {
      routes:
        | '/admin/inventory/Stock'
      views:
        | never
    }
    'resources/js/admin/pages/inventory/stock-adjusment.vue': {
      routes:
        | '/admin/inventory/stock-adjusment'
      views:
        | never
    }
    'resources/js/admin/pages/login.vue': {
      routes:
        | '/admin/login'
      views:
        | never
    }
    'resources/js/admin/pages/partnership/Genealogy.vue': {
      routes:
        | '/admin/partnership/Genealogy'
      views:
        | never
    }
    'resources/js/admin/pages/partnership/member-downgrades.vue': {
      routes:
        | '/admin/partnership/member-downgrades'
      views:
        | never
    }
    'resources/js/admin/pages/partnership/member-registration.vue': {
      routes:
        | '/admin/partnership/member-registration'
      views:
        | never
    }
    'resources/js/admin/pages/partnership/member-stock.vue': {
      routes:
        | '/admin/partnership/member-stock'
      views:
        | never
    }
    'resources/js/admin/pages/partnership/member-upgrades.vue': {
      routes:
        | '/admin/partnership/member-upgrades'
      views:
        | never
    }
    'resources/js/admin/pages/partnership/members.vue': {
      routes:
        | '/admin/partnership/members'
      views:
        | never
    }
    'resources/js/admin/pages/partnership/registration-approvals.vue': {
      routes:
        | '/admin/partnership/registration-approvals'
      views:
        | never
    }
    'resources/js/admin/pages/partnership/sales-report.vue': {
      routes:
        | '/admin/partnership/sales-report'
      views:
        | never
    }
    'resources/js/admin/pages/partnership/stockists.vue': {
      routes:
        | '/admin/partnership/stockists'
      views:
        | never
    }
    'resources/js/admin/pages/product/categories.vue': {
      routes:
        | '/admin/product/categories'
      views:
        | never
    }
    'resources/js/admin/pages/product/prices.vue': {
      routes:
        | '/admin/product/prices'
      views:
        | never
    }
    'resources/js/admin/pages/product/products.vue': {
      routes:
        | '/admin/product/products'
      views:
        | never
    }
    'resources/js/admin/pages/profile.vue': {
      routes:
        | '/admin/profile'
      views:
        | never
    }
    'resources/js/admin/pages/report/cash-receipts.vue': {
      routes:
        | '/admin/report/cash-receipts'
      views:
        | never
    }
    'resources/js/admin/pages/report/inventory-value.vue': {
      routes:
        | '/admin/report/inventory-value'
      views:
        | never
    }
    'resources/js/admin/pages/report/profit-loss.vue': {
      routes:
        | '/admin/report/profit-loss'
      views:
        | never
    }
    'resources/js/admin/pages/reset-password.vue': {
      routes:
        | '/admin/reset-password'
      views:
        | never
    }
    'resources/js/admin/pages/rewards/annual.vue': {
      routes:
        | '/admin/rewards/annual'
      views:
        | never
    }
    'resources/js/admin/pages/rewards/monthly.vue': {
      routes:
        | '/admin/rewards/monthly'
      views:
        | never
    }
    'resources/js/admin/pages/rewards/point-achievement-report.vue': {
      routes:
        | '/admin/rewards/point-achievement-report'
      views:
        | never
    }
    'resources/js/admin/pages/rewards/profit-sharing.vue': {
      routes:
        | '/admin/rewards/profit-sharing'
      views:
        | never
    }
    'resources/js/admin/pages/rewards/profit-sharing-history.vue': {
      routes:
        | '/admin/rewards/profit-sharing-history'
      views:
        | never
    }
    'resources/js/admin/pages/rewards/stockist.vue': {
      routes:
        | '/admin/rewards/stockist'
      views:
        | never
    }
    'resources/js/admin/pages/stc/saldo.vue': {
      routes:
        | '/admin/stc/saldo'
      views:
        | never
    }
    'resources/js/admin/pages/stc/topup.vue': {
      routes:
        | '/admin/stc/topup'
      views:
        | never
    }
    'resources/js/admin/pages/system/administrators.vue': {
      routes:
        | '/admin/system/administrators'
      views:
        | never
    }
    'resources/js/admin/pages/system/commission-config.vue': {
      routes:
        | '/admin/system/commission-config'
      views:
        | never
    }
    'resources/js/admin/pages/system/menus.vue': {
      routes:
        | '/admin/system/menus'
      views:
        | never
    }
    'resources/js/admin/pages/system/partnership-config.vue': {
      routes:
        | '/admin/system/partnership-config'
      views:
        | never
    }
    'resources/js/admin/pages/system/roles.vue': {
      routes:
        | '/admin/system/roles'
      views:
        | never
    }
    'resources/js/admin/pages/transactions/payment-verification.vue': {
      routes:
        | '/admin/transactions/payment-verification'
      views:
        | never
    }
    'resources/js/admin/pages/transactions/sales-orders.vue': {
      routes:
        | '/admin/transactions/sales-orders'
      views:
        | never
    }
    'resources/js/admin/pages/transactions/sales-returns.vue': {
      routes:
        | '/admin/transactions/sales-returns'
      views:
        | never
    }
    'resources/js/admin/pages/transactions/stock-screening.vue': {
      routes:
        | '/admin/transactions/stock-screening'
      views:
        | never
    }
    'resources/js/admin/pages/user-analytic/index.vue': {
      routes:
        | '/admin/user-analytic/'
      views:
        | never
    }
    'resources/js/member/pages/[...all].vue': {
      routes:
        | '/member/[...all]'
      views:
        | never
    }
    'resources/js/member/pages/Dashboard.vue': {
      routes:
        | '/member/Dashboard'
      views:
        | never
    }
    'resources/js/member/pages/forgot-password.vue': {
      routes:
        | '/member/forgot-password'
      views:
        | never
    }
    'resources/js/member/pages/login.vue': {
      routes:
        | '/member/login'
      views:
        | never
    }
    'resources/js/member/pages/menus/index.vue': {
      routes:
        | '/member/menus/'
      views:
        | never
    }
    'resources/js/member/pages/network/index.vue': {
      routes:
        | '/member/network/'
      views:
        | never
    }
    'resources/js/member/pages/network/registrations/index.vue': {
      routes:
        | '/member/network/registrations/'
      views:
        | never
    }
    'resources/js/member/pages/network/registrations/[id].vue': {
      routes:
        | '/member/network/registrations/[id]'
      views:
        | never
    }
    'resources/js/member/pages/notifications.vue': {
      routes:
        | '/member/notifications'
      views:
        | never
    }
    'resources/js/member/pages/profile/index.vue': {
      routes:
        | '/member/profile/'
      views:
        | never
    }
    'resources/js/member/pages/profile/address.vue': {
      routes:
        | '/member/profile/address'
      views:
        | never
    }
    'resources/js/member/pages/profile/address-form.vue': {
      routes:
        | '/member/profile/address-form'
      views:
        | never
    }
    'resources/js/member/pages/profile/bank.vue': {
      routes:
        | '/member/profile/bank'
      views:
        | never
    }
    'resources/js/member/pages/profile/bank-form.vue': {
      routes:
        | '/member/profile/bank-form'
      views:
        | never
    }
    'resources/js/member/pages/profile/edit.vue': {
      routes:
        | '/member/profile/edit'
      views:
        | never
    }
    'resources/js/member/pages/profile/partnership.vue': {
      routes:
        | '/member/profile/partnership'
      views:
        | never
    }
    'resources/js/member/pages/profile/security.vue': {
      routes:
        | '/member/profile/security'
      views:
        | never
    }
    'resources/js/member/pages/reset-password.vue': {
      routes:
        | '/member/reset-password'
      views:
        | never
    }
    'resources/js/member/pages/rewards/index.vue': {
      routes:
        | '/member/rewards/'
      views:
        | never
    }
    'resources/js/member/pages/rewards/annual.vue': {
      routes:
        | '/member/rewards/annual'
      views:
        | never
    }
    'resources/js/member/pages/rewards/monthly/index.vue': {
      routes:
        | '/member/rewards/monthly/'
      views:
        | never
    }
    'resources/js/member/pages/rewards/monthly/[id].vue': {
      routes:
        | '/member/rewards/monthly/[id]'
      views:
        | never
    }
    'resources/js/member/pages/rewards/sharing/index.vue': {
      routes:
        | '/member/rewards/sharing/'
      views:
        | never
    }
    'resources/js/member/pages/rewards/sharing/[id].vue': {
      routes:
        | '/member/rewards/sharing/[id]'
      views:
        | never
    }
    'resources/js/member/pages/rewards/stockist/index.vue': {
      routes:
        | '/member/rewards/stockist/'
      views:
        | never
    }
    'resources/js/member/pages/rewards/stockist/[id].vue': {
      routes:
        | '/member/rewards/stockist/[id]'
      views:
        | never
    }
    'resources/js/member/pages/stock/index.vue': {
      routes:
        | '/member/stock/'
      views:
        | never
    }
    'resources/js/member/pages/stock/adjustment.vue': {
      routes:
        | '/member/stock/adjustment'
      views:
        | never
    }
    'resources/js/member/pages/stock/mutation.vue': {
      routes:
        | '/member/stock/mutation'
      views:
        | never
    }
    'resources/js/member/pages/stock/returns/index.vue': {
      routes:
        | '/member/stock/returns/'
      views:
        | never
    }
    'resources/js/member/pages/stock/returns/[id].vue': {
      routes:
        | '/member/stock/returns/[id]'
      views:
        | never
    }
    'resources/js/member/pages/stock/returns/create.vue': {
      routes:
        | '/member/stock/returns/create'
      views:
        | never
    }
    'resources/js/member/pages/transactions/index.vue': {
      routes:
        | '/member/transactions/'
      views:
        | never
    }
    'resources/js/member/pages/transactions/goods-receipts/index.vue': {
      routes:
        | '/member/transactions/goods-receipts/'
      views:
        | never
    }
    'resources/js/member/pages/transactions/goods-receipts/[id].vue': {
      routes:
        | '/member/transactions/goods-receipts/[id]'
      views:
        | never
    }
    'resources/js/member/pages/transactions/orders/index.vue': {
      routes:
        | '/member/transactions/orders/'
      views:
        | never
    }
    'resources/js/member/pages/transactions/orders/[id].vue': {
      routes:
        | '/member/transactions/orders/[id]'
      views:
        | never
    }
    'resources/js/member/pages/transactions/orders/create.vue': {
      routes:
        | '/member/transactions/orders/create'
      views:
        | never
    }
    'resources/js/member/pages/transactions/orders/payment.vue': {
      routes:
        | '/member/transactions/orders/payment'
      views:
        | never
    }
    'resources/js/member/pages/transactions/sales/index.vue': {
      routes:
        | '/member/transactions/sales/'
      views:
        | never
    }
    'resources/js/member/pages/transactions/sales/[id].vue': {
      routes:
        | '/member/transactions/sales/[id]'
      views:
        | never
    }
    'resources/js/member/pages/transactions/sales/create.vue': {
      routes:
        | '/member/transactions/sales/create'
      views:
        | never
    }
    'resources/js/member/pages/transactions/sales/payment.vue': {
      routes:
        | '/member/transactions/sales/payment'
      views:
        | never
    }
    'resources/js/member/pages/transactions/sales/shipping.vue': {
      routes:
        | '/member/transactions/sales/shipping'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
