<?php

namespace App\Http\Requests\Api\V1\Concerns;

use App\Models\Member;
use App\Models\MemberRegistration;
use App\Models\RefBank;
use App\Models\RefCity;
use App\Models\RefCountry;
use App\Models\RefDistrict;
use App\Models\RefProvince;
use App\Models\RefSubdistrict;
use App\Support\PhoneNumber;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Validator;

trait HasMemberRegistrationRules
{
    /** @return array<string, mixed> */
    protected function registrationRules(): array
    {
        return [
            'name' => ['required', 'string', 'max:100'],
            'email' => ['nullable', 'email', 'max:100'],
            'mobile_phone' => ['required', 'string', 'regex:/^\+62[0-9]{8,13}$/'],
            'gender' => ['required', 'in:Laki-laki,Perempuan'],
            'birth_date' => ['required', 'date', 'before:today'],
            'address' => ['required', 'string', 'max:255'],
            'province_id' => [
                'required',
                'string',
                'max:2',
                Rule::exists((new RefProvince)->getTable(), 'province_id'),
            ],
            'city_id' => [
                'required',
                'string',
                'max:4',
                Rule::exists((new RefCity)->getTable(), 'city_id'),
            ],
            'district_id' => [
                'required',
                'string',
                'max:6',
                Rule::exists((new RefDistrict)->getTable(), 'district_id'),
            ],
            'subdistrict_id' => [
                'required',
                'integer',
                Rule::exists((new RefSubdistrict)->getTable(), 'subdistrict_id'),
            ],
            'country_id' => [
                'sometimes',
                'integer',
                Rule::exists((new RefCountry)->getTable(), 'country_id')
                    ->where('country_is_active', '1'),
            ],
            'bank_id' => [
                'nullable',
                'integer',
                Rule::exists((new RefBank)->getTable(), 'bank_id')
                    ->where('bank_is_active', 1),
            ],
            'bank_account_name' => ['nullable', 'required_with:bank_id', 'string', 'max:50'],
            'bank_account_number' => ['nullable', 'required_with:bank_id', 'string', 'max:50'],
            'bank_city' => ['nullable', 'string', 'max:50'],
            'bank_branch' => ['nullable', 'string', 'max:50'],
            'identity_type' => ['required', 'in:KTP,SIM,PASPOR'],
            'identity_no' => ['required', 'string', 'max:20'],
            'identity_image_url' => ['nullable', 'string', 'max:255'],
            'nib' => ['nullable', 'string', 'max:20'],
            // Username dibuat dari kode mitra ketika pengajuan disetujui admin.
            'username' => ['prohibited'],
            // Credentials are generated by the server after approval.
            'password' => ['prohibited'],
            'password_confirmation' => ['prohibited'],
        ];
    }

    /** @return array<int, callable> */
    protected function registrationValidators(): array
    {
        return [
            function (Validator $validator): void {
                $this->validateRegion($validator);
                $this->validateUniqueApplicant($validator);
            },
        ];
    }

    protected function prepareForValidation(): void
    {
        if ($this->has('mobile_phone')) {
            $this->merge(['mobile_phone' => PhoneNumber::normalize($this->input('mobile_phone'))]);
        }
    }

    /** @return array<string, string> */
    protected function registrationAttributes(): array
    {
        return [
            'name' => 'nama lengkap',
            'email' => 'email',
            'mobile_phone' => 'nomor WhatsApp',
            'gender' => 'jenis kelamin',
            'birth_date' => 'tanggal lahir',
            'address' => 'alamat',
            'province_id' => 'provinsi',
            'city_id' => 'kota/kabupaten',
            'district_id' => 'kecamatan',
            'subdistrict_id' => 'kelurahan/desa',
            'country_id' => 'negara',
            'bank_id' => 'bank',
            'bank_account_name' => 'nama pemilik rekening',
            'bank_account_number' => 'nomor rekening',
            'bank_city' => 'kota bank',
            'bank_branch' => 'cabang bank',
            'identity_type' => 'jenis identitas',
            'identity_no' => 'nomor identitas',
            'identity_image_url' => 'dokumen identitas',
            'nib' => 'NIB',
            'username' => 'username mitra',
            'password' => 'kata sandi',
            'password_confirmation' => 'konfirmasi kata sandi',
        ];
    }

    private function validateRegion(Validator $validator): void
    {
        $provinceId = $this->input('province_id');
        $cityId = $this->input('city_id');
        $districtId = $this->input('district_id');
        $subdistrictId = $this->input('subdistrict_id');

        if (! is_string($provinceId) || ! is_string($cityId) || ! is_string($districtId)
            || ! is_numeric($subdistrictId)) {
            return;
        }

        $valid = RefCity::query()
            ->where('city_id', $cityId)
            ->where('city_province_id', $provinceId)
            ->exists()
            && RefDistrict::query()
                ->where('district_id', $districtId)
                ->where('district_city_id', $cityId)
                ->exists()
            && RefSubdistrict::query()
                ->where('subdistrict_id', (int) $subdistrictId)
                ->where('subdistrict_district_id', (int) $districtId)
                ->exists();

        if (! $valid) {
            $validator->errors()->add(
                'province_id',
                'Wilayah provinsi, kota, kecamatan, dan kelurahan tidak saling sesuai.'
            );
        }
    }

    private function validateUniqueApplicant(Validator $validator): void
    {
        $pendingStatuses = ['requested', 'approved'];

        $checks = [
            'mobile_phone' => [
                'member' => 'member_mobilephone',
                'registration_column' => 'member_registration_mobilephone',
                'message' => 'Nomor WhatsApp sudah digunakan atau masih dalam proses pendaftaran.',
            ],
            'identity_no' => [
                'member' => 'member_identity_no',
                'registration_column' => 'member_registration_identity_no',
                'message' => 'Nomor identitas sudah digunakan atau masih dalam proses pendaftaran.',
            ],
        ];

        foreach ($checks as $input => $check) {
            $value = $this->input($input);

            if (! is_string($value) || $value === '') {
                continue;
            }

            $existsInMember = $check['member'] !== null
                && Member::query()
                    ->where($check['member'], $value)
                    ->where('member_status', '!=', 3)
                    ->exists();
            $existsInRegistration = MemberRegistration::query()
                ->where($check['registration_column'], $value)
                ->whereIn('member_registration_status', $pendingStatuses)
                ->exists();

            if ($existsInMember || $existsInRegistration) {
                $validator->errors()->add($input, $check['message']);
            }
        }
    }
}
